name: CI

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          version: 10.5
          php_version: 8.0
          configuration: phpunit.xml